name: sample-workflow
on: [push]
jobs: 
  explore-first-github-workflow: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo job trigger
        run: echo "the job was automatically triggered by a ${{ github.event_name }} event."
      - name: Echo runner OS
        run: echo "This job is now running on a ${{ runner.os }} server hosted by Github!"
      - name: Echo branch and repository name
        run: echo "the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Echo repository clone
        run: echo "The ${{ github.repository }} repository has been cloned to the runner." 
      - name: Echo ready to test code
        run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Echo job status
        run: echo "This job's status is ${{ job.status }}."
